### ISSUE TITLE
回答の削除時に確認のポップが複数回上がる

### ISSUE THREAD

**Issue by n0dam1** [NaitoYuki/StackOverFlow#31]

**Comment by G-shuu** [comment]
今確認してみたら、大丈夫でした！
昨日確認した際は、削除時に「本当に削除していいですか」のポップが出て、OKを押しても、
同じポップが再度上がってくるようでした。

**Comment by n0dam1** [comment]
承知しました、ありがとうございます！このissueは閉じておきます。
