### ISSUE TITLE
質問モデルを作成する

### ISSUE THREAD

**Issue by n0dam1** [NaitoYuki/StackOverFlow#4]
`Question`モデルを作成する

- [x] カラム
- [x] ユーザーと質問が紐付いている。ユーザー：質問が１：多
- [x] validation

**Comment by n0dam1** [comment]
### カラム ###
タイトル：`title:string`
本文：`content:text`

### ユーザーと質問が紐づいている。
user.rbに
`has_many :questions, dependent: :destroy`、
question.rbに
`belongs_to :user`
を追加。

### validation ###
userモデルのtitle,contentに必須チェックを追加
```
validate :title, presence: true
validate :content, presence: true
```

**Comment by NaitoYuki** [comment]
#19 
確認済み。クローズします。
